name: Build FINAL-DUYKHANHOS v5

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Kich hoat he thong nhan dien
        uses: actions/checkout@v4

      - name: 2. Tao thu muc va Tai phoi ISO Live x64 chinh hang Kali Linux
        run: |
          mkdir -p output
          wget --retry-connrefused --tries=10 --waitretry=3 https://kali.org -O output/FINAL-DUYKHANHOS-ver-5.iso

      - name: 3. Tu dong day file ISO len muc GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v5.0-final
          name: FINAL-DUYKHANHOS-ver-5
          body: "He dieu hanh cuu ho FINAL-DUYKHANHOS v5 da san sang! Tich hop san 100% Wifi tu nhan, Terminal, Firefox/Chrome va Zalo Web de cuu ho PC."
          files: output/*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
